services:
  db:
    image: postgres:16-alpine
    container_name: tech-challenge-db
    environment:
      POSTGRES_DB: usuarios
      POSTGRES_USER: tech-challenge
      POSTGRES_PASSWORD: tech-challenge
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tech-challenge -d usuarios"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: tech-challenge-app
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://db:5432/usuarios
      DB_USERNAME: tech-challenge
      DB_PASSWORD: tech-challenge
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
