spring.application.name=usuarios

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/usuarios}
spring.datasource.username=${DB_USERNAME:tech-challenge}
spring.datasource.password=${DB_PASSWORD:tech-challenge}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
